### All the usual arithmetic operators (+, -, *, /, //, **, etc.) can be used with ndarrays. They apply elementwise. but with a condition. The arrays must have the same shape. If they do not, NumPy will apply the broadcasting rules.

In [1]:
import numpy as np

arr_1=np.array([1,2,3])
arr_2=np.array([4,5,6])
#addition
arr_1+arr_2

array([5, 7, 9])

In [3]:
#subtraction
arr_1-arr_2

array([-3, -3, -3])

In [5]:
#multiplication
arr_1*arr_2

array([ 4, 10, 18])

In [7]:
#modulo (remainder)
arr_1%arr_2

array([1, 2, 3])

In [8]:
#divide
arr_1/arr_2

array([0.25, 0.4 , 0.5 ])

In [10]:
#In Python, // is the floor division operator. It divides two numbers and truncates the result to the nearest integer less than or equal to the division result.
arr_2//arr_1

array([4, 2, 2])

In [11]:
#In Python, ** is the exponentiation operator. It is used to raise a number to the power of another number.
arr_2**arr_1

array([  4,  25, 216])

## when arrays ares not of the same shape, then broadcasting is applied.

In [12]:
# In general, when NumPy expects arrays of the same shape but finds that this is not the case, it applies the so-called broadcasting rules:

## First rule
If the arrays do not have the same rank, then a 1 will be prepended to the smaller ranking arrays until their ranks match.

In [18]:
arr_1=np.arange(4).reshape(1,1,4)

In [16]:
arr_1

array([[[0, 1, 2, 3, 4]]])

In [17]:
#rank of array
arr_1.ndim

3

### Now let's try to add a 1D array of shape (4,) to this 3D array of shape (1,1,5). Applying the first rule of broadcasting!

In [22]:
# the one-d array is [10,20,30,40]
# now adding the one-d array into a 3-d array.
arr_1+[10,20,30,40]
# the one-d array is transformed into

array([[[10, 21, 32, 43]]])