# Indexing of One-dimensional arrays
##### One-dimensional NumPy arrays can be accessed more or less like regular python arrays:

In [169]:
import numpy as np
arr_1=np.array([6,7,8,9,10,11,12])
arr_1[5]

np.int64(11)

In [170]:
# here the last index i.e, 6 is excluded
arr_1[2:6]

array([ 8,  9, 10, 11])

In [171]:
# -1 index belongs to the last element in the array
arr_1[4:-1]

array([10, 11])

In [172]:
#advanced slicing
#The double colons :: in slicing, such as arr_1[2::2], indicate advanced slicing in Python, where you specify the start(inclusive), stop(exclusive), and step values for slicing an array or list.
#array[start:stop:step]
# if stop is emitted, it defaults to the end of the array.
arr_1[3::2]

array([ 9, 11])

In [173]:
# start: Omitted, so it defaults to the beginning of the array.
# stop: Omitted, so it defaults to the end of the array.
# step=-1: A negative step indicates moving through the array in reverse order.
#These operation does not modify the original array; it returns a new reversed array.
arr_1[::-1]

array([12, 11, 10,  9,  8,  7,  6])

In [174]:
# modifying array elements
#4th index element is modified
arr_1[4]=56
arr_1

array([ 6,  7,  8,  9, 56, 11, 12])

In [175]:
# modifying a slice of an array
arr_1[5:7]=[55,99]
arr_1

array([ 6,  7,  8,  9, 56, 55, 99])

## Differences with regular python arrays

In [180]:
#Contrary to regular python arrays, if you assign a single value to an ndarray slice, it is copied across the whole slice, thanks to broadcasting.
print(f"before modifying the array: {arr_1}")
arr_1[2:5]=-4
print(f"after modifying the array: {arr_1}")

before modifying the array: [ 6  7 -4 -4 -4 55 99]
after modifying the array: [ 6  7 -4 -4 -4 55 99]


In [181]:
#Also, you cannot grow or shrink ndarrays this way:
try:
    arr_1[2:5] = [1,2,3,4,5,6]  # too long
except ValueError as e:
    print(e)

could not broadcast input array from shape (6,) into shape (3,)


In [182]:
#Also, you cannot grow or shrink ndarrays this way:
try:
    arr_1[2:5] = [1,2]  # too short
except ValueError as e:
    print(e)

could not broadcast input array from shape (2,) into shape (3,)


In [183]:
#cannot delete elements either:
try:
    del arr_1[3:6]
except ValueError as e:
    print(e)

cannot delete array elements


In [184]:
#Important:  ndarray slices are actually views on the same data buffer. This means that if you create a slice and modify it, you are actually going to modify the original ndarray as well!
arr_1_slice=arr_1[3:6]
arr_1_slice

array([-4, -4, 55])

In [186]:
#modified the sliced array
arr_1_slice[2]=1099
arr_1_slice

array([  -4,   -4, 1099])

In [187]:
#checking whether the sliced array modified the actual array
arr_1
#yup, it is modified.

array([   6,    7,   -4,   -4,   -4, 1099,   99])

In [188]:
#similarly, modifying the actual array modifies the sliced array.
arr_1[5]=1098
arr_1

array([   6,    7,   -4,   -4,   -4, 1098,   99])

In [191]:
#checking if the sliced array is modified or not. changed from 1099 to 1098
arr_1_slice
#yup , it is modified.

array([  -4,   -4, 1098])

In [193]:
#If you want a copy of the array data, you need to use the copy method:
arr_1_copy=arr_1.copy()
arr_1_copy

array([   6,    7,   -4,   -4,   -4, 1098,   99])

In [195]:
arr_1_copy[5]=666
arr_1_copy

array([  6,   7,  -4,  -4,  -4, 666,  99])

In [197]:
#you can see, changing the copied array does not change the original array
arr_1

array([   6,    7,   -4,   -4,   -4, 1098,   99])