# 1. Array data

In [159]:
import numpy as np
np_array=np.array([1,2,3,4,5])

In [160]:
np_array.dtype

dtype('int64')

In [161]:
# setting the data type
np_array=np.array([1,2,3,4,5],dtype=float)
np_array.dtype

dtype('float64')

In [162]:
# checking the item size
#The itemsize attribute of a NumPy array returns the size (in bytes) of each element in the array.
np_array.itemsize

8

# 2.  Reshaping an Array.

## 2.1 In place
#### The shape attribute in NumPy is used to get or set the dimensions of a NumPy array. In-place manipulation of the shape attribute refers to directly modifying the shape of an array using assignment (=), which alters the array’s dimensions without creating a new array.

In [163]:

np_array=np.arange(30)
np_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [164]:
#changing the shape of the array. only one condition: the size of the array must remain the same.
np_array.shape=(6,5)
np_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [165]:
# checking the dimension of the array using ndim attribute
np_array.ndim

2

In [166]:
# If a NumPy array has its shape set to (5, 2, 3), it means the array has three dimensions, where:
# 5: The array has 5 blocks (the first dimension).
# 2: Each block contains 2 rows (the second dimension).
# 3: Each row contains 3 columns (the third dimension).


# reshaping again to 3-d
np_array.shape=(5,2,3)
np_array

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]]])

In [167]:
#checking the rank. (rank refers to number of dimensions)
np_array.ndim

3

## 2.2 reshape() function

#### The reshape function returns a new ndarray object pointing at the same data. This means that modifying one array will also modify the other.

In [168]:
np_reshape=np_array.reshape(10,3)

In [169]:
np_reshape

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [170]:
# Set item at row 5, col 2 to 454.
np_reshape[5,2]=454

In [171]:
np_reshape

array([[  0,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11],
       [ 12,  13,  14],
       [ 15,  16, 454],
       [ 18,  19,  20],
       [ 21,  22,  23],
       [ 24,  25,  26],
       [ 27,  28,  29]])

In [172]:
# now checking if the changes have been reflected in np_array. you can check the corresponding element has been modified in this array also.
np_array

array([[[  0,   1,   2],
        [  3,   4,   5]],

       [[  6,   7,   8],
        [  9,  10,  11]],

       [[ 12,  13,  14],
        [ 15,  16, 454]],

       [[ 18,  19,  20],
        [ 21,  22,  23]],

       [[ 24,  25,  26],
        [ 27,  28,  29]]])

## 2.3 ravel()

In [173]:
# The ravel() function in NumPy returns a flattened (1D) view of the original array whenever possible. If a view is not feasible, it creates a new array.
# we can store the view in a new array.
np_ravel=np_array.ravel()

In [174]:
np_ravel

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16, 454,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [175]:
# note modifying the view also modifies the original array.
np_ravel[10]=4544

In [176]:
np_ravel

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9, 4544,
         11,   12,   13,   14,   15,   16,  454,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29])

In [177]:
np_array

array([[[   0,    1,    2],
        [   3,    4,    5]],

       [[   6,    7,    8],
        [   9, 4544,   11]],

       [[  12,   13,   14],
        [  15,   16,  454]],

       [[  18,   19,   20],
        [  21,   22,   23]],

       [[  24,   25,   26],
        [  27,   28,   29]]])