In [1]:
## The conditional operators also apply elementwise:

In [2]:
import numpy as np

arr_1=np.array([20,-15,55,60,58])
arr_1<[20,30,40,50,70]

array([False,  True, False, False,  True])

In [3]:
#using broadcasting
arr_1<24
# as 24 expands itself to [24,24,24,24,24]

array([ True,  True, False, False, False])

In [4]:
#getting the values.
arr_1[arr_1<24]

array([ 20, -15])