In [70]:
import numpy as np

In [71]:
# with np.zeros()
#by default it creates array of float type but if we specify dtype=int, it creates an array of int type.
# one-dimensional i,e, vector and z in naming indicates zero.
z_vec=np.zeros(5,dtype=int)
z_vec

array([0, 0, 0, 0, 0])

In [72]:
#2-d array
z_mat=np.zeros((5,5))
z_mat

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [73]:
z_mat.shape

(5, 5)

In [74]:
# for dimension
z_mat.ndim

2

In [75]:
#for size-no of elements in an array is size of an element
z_mat.size

25

In [76]:
#rank-no of dimensions of an array

In [77]:
#creating an array with rank 3 i.e, 3-dimensional array having dimension length (3,4,5)
#A 3D NumPy array can be thought of as a cube or a stack of 2D arrays (matrices). It has three axes:

#Axis 0: depth (number of 2D arrays stacked)
#Axis 1: rows in each 2D array
#Axis 2: columns in each 2D array

z_arr=np.zeros((3,4,5))

In [78]:
z_arr

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [79]:
#Array-type: numpy array have type i.e, ndarray
type(z_arr)

numpy.ndarray

In [80]:
#Creating Numpy array using np.ones()
# one- dimensional  i.e, vector and o in the naming represents one
o_vec=np.ones(5)
o_vec

array([1., 1., 1., 1., 1.])

In [81]:
#two- dimensional i.e, matrix
o_mat=np.ones((5,5))
o_mat

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [85]:
# Creating numpy array using np.full with a specific value
f_arr=np.full((3,3),2)


In [84]:
f_arr

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [88]:
f_mat=np.full((4,5),np.sqrt(5))
f_mat

array([[2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [90]:
#Creating array using : np.empty
#An uninitialized 2x3 array (its content is not predictable, as it is whatever is in memory at that point):

e_mat=np.empty((2,3))
e_mat

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.24610994e-306, 9.34605037e-307, 1.05699581e-307]])

In [93]:
#Initializing a numpy array using a regular python list by calling the array function
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [95]:
# Creating an array using np.arange(). 
#np.arange() creates a NumPy array with evenly spaced values within a specified interval. It's similar to Python's range() but returns a NumPy array instead of a range object.
# and you can also provide a step parameter.

np.arange(2,6)

array([2, 3, 4, 5])

In [98]:
#using float values and step parameter: 2
np.arange(11.0,18.5,2)

array([11., 13., 15., 17.])