In [1]:
import numpy as np

#calculating mean using mean()
#Note that this computes the mean of all elements in the `ndarray`, regardless of its shape.

arr_1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr_1.mean()


np.float64(5.5)

In [2]:
# some useful numpy array methods.
#getting the minimum value
arr_1.min()

np.int64(1)

In [3]:
#getting the maximum value
arr_1.max()

np.int64(10)

In [4]:
#sum of all elements of an array.
arr_1.sum()

np.int64(55)

In [5]:
# product of all values
arr_1.prod()

np.int64(3628800)

In [7]:
#The standard deviation is the square root of the average of the squared differences between each number and the mean.
arr_1.std()

np.float64(2.8722813232690143)

In [8]:
# variance value:the average of the squared differences between each number and the mean.
arr_1.var()

np.float64(8.25)

### These functions accept an optional argument axis which lets you ask for the operation to be performed on elements along the given axis. For example:

In [10]:
arr2=np.arange(30).reshape(6,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [11]:
arr2.sum(axis=0)

array([75, 81, 87, 93, 99])

In [16]:
arr3=arr2.reshape(2,5,3)
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [17]:
arr3.sum(axis=0)
#When you perform a sum along axis=0, values from corresponding positions in each block (along the first dimension) are added together. This means:

#Sum the first elements of each block.
#Sum the second elements of each block, and so on.

array([[15, 17, 19],
       [21, 23, 25],
       [27, 29, 31],
       [33, 35, 37],
       [39, 41, 43]])

In [18]:
arr3.sum(axis=1)
#When you sum along axis=1, you combine rows within each block. This means:

#For each block, sum the values across the rows row-wise (at each column position).

array([[ 30,  35,  40],
       [105, 110, 115]])