In [191]:
import numpy as np

#calculating mean using mean()
#Note that this computes the mean of all elements in the `ndarray`, regardless of its shape.

arr_1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr_1.mean()


np.float64(5.5)

In [192]:
# some useful numpy array methods.
#getting the minimum value
arr_1.min()

np.int64(1)

In [193]:
#getting the maximum value
arr_1.max()

np.int64(10)

In [194]:
#sum of all elements of an array.
arr_1.sum()

np.int64(55)

In [195]:
# product of all values
arr_1.prod()

np.int64(3628800)

In [196]:
#The standard deviation is the square root of the average of the squared differences between each number and the mean.
arr_1.std()

np.float64(2.8722813232690143)

In [197]:
# variance value:the average of the squared differences between each number and the mean.
arr_1.var()

np.float64(8.25)

### These functions accept an optional argument axis which lets you ask for the operation to be performed on elements along the given axis. For example:

In [198]:
arr2=np.arange(30).reshape(6,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [199]:
arr2.sum(axis=0)

array([75, 81, 87, 93, 99])

In [200]:
arr3=arr2.reshape(2,5,3)
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [201]:
arr3.sum(axis=0)
#When you perform a sum along axis=0, values from corresponding positions in each block (along the first dimension) are added together. This means:

#Sum the first elements of each block.
#Sum the second elements of each block, and so on.

array([[15, 17, 19],
       [21, 23, 25],
       [27, 29, 31],
       [33, 35, 37],
       [39, 41, 43]])

In [202]:
arr3.sum(axis=1)
#When you sum along axis=1, you combine rows within each block. This means:
#For each block, sum the values across the rows row-wise (at each column position).

array([[ 30,  35,  40],
       [105, 110, 115]])

In [203]:
#When you perform arr3.sum(axis=(0, 1, 2)) on a NumPy array, it means you're summing all elements across all three axes of a 3D array (axis=0, axis=1, and axis=2), effectively collapsing the array into a single scalar value.
arr3.sum(axis=(0,1,2))

np.int64(435)

In [204]:
#sum over matrices and columns
arr3.sum(axis=(0,2))

array([ 51,  69,  87, 105, 123])

In [205]:
arr3.sum(axis=(0,1))
#sum over matrices and along rows

array([135, 145, 155])

# Universal Functions -ufunc
### NumPy also provides fast elementwise functions called universal functions, or ufunc.

In [206]:
arr4=np.array([[1,2,-3,4.5,5],
               [6,-7,8.6,9,10]])
arr4

array([[ 1. ,  2. , -3. ,  4.5,  5. ],
       [ 6. , -7. ,  8.6,  9. , 10. ]])

In [207]:
#element wise square of arr4
np.square(arr4)

array([[  1.  ,   4.  ,   9.  ,  20.25,  25.  ],
       [ 36.  ,  49.  ,  73.96,  81.  , 100.  ]])

In [208]:
#element wise sqrt of arr4
np.sqrt(arr4)


/var/folders/yt/nk9t1qyn7vx4jvyz_r5gsfwr0000gr/T/ipykernel_65687/3612839652.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr4)


array([[1.        , 1.41421356,        nan, 2.12132034, 2.23606798],
       [2.44948974,        nan, 2.93257566, 3.        , 3.16227766]])

In [209]:
np.absolute(arr4)

array([[ 1. ,  2. ,  3. ,  4.5,  5. ],
       [ 6. ,  7. ,  8.6,  9. , 10. ]])

In [210]:
print("Original array")
print(arr4)
for func in (np.abs, np.sqrt, np.exp, np.log, np.sign, np.ceil, np.modf, np.isnan, np.cos):
    print("\n",func.__name__)
    print(func(arr4))

Original array
[[ 1.   2.  -3.   4.5  5. ]
 [ 6.  -7.   8.6  9.  10. ]]

 absolute
[[ 1.   2.   3.   4.5  5. ]
 [ 6.   7.   8.6  9.  10. ]]

 sqrt
[[1.         1.41421356        nan 2.12132034 2.23606798]
 [2.44948974        nan 2.93257566 3.         3.16227766]]

 exp
[[2.71828183e+00 7.38905610e+00 4.97870684e-02 9.00171313e+01
  1.48413159e+02]
 [4.03428793e+02 9.11881966e-04 5.43165959e+03 8.10308393e+03
  2.20264658e+04]]

 log
[[0.         0.69314718        nan 1.5040774  1.60943791]
 [1.79175947        nan 2.1517622  2.19722458 2.30258509]]

 sign
[[ 1.  1. -1.  1.  1.]
 [ 1. -1.  1.  1.  1.]]

 ceil
[[ 1.  2. -3.  5.  5.]
 [ 6. -7.  9.  9. 10.]]

 modf
(array([[ 0. ,  0. , -0. ,  0.5,  0. ],
       [ 0. , -0. ,  0.6,  0. ,  0. ]]), array([[ 1.,  2., -3.,  4.,  5.],
       [ 6., -7.,  8.,  9., 10.]]))

 isnan
[[False False False False False]
 [False False False False False]]

 cos
[[ 0.54030231 -0.41614684 -0.9899925  -0.2107958   0.28366219]
 [ 0.96017029  0.75390225 -0.6787200

/var/folders/yt/nk9t1qyn7vx4jvyz_r5gsfwr0000gr/T/ipykernel_65687/3806645518.py:5: RuntimeWarning: invalid value encountered in sqrt
  print(func(arr4))
/var/folders/yt/nk9t1qyn7vx4jvyz_r5gsfwr0000gr/T/ipykernel_65687/3806645518.py:5: RuntimeWarning: invalid value encountered in log
  print(func(arr4))


In [211]:
#The two warnings are due to the fact that sqrt() and log() are undefined for negative numbers, which is why there is a np.nan value in the first cell of the output of these two functions.

# Binary ufuncs

In [212]:
#There are also many binary ufuncs, that apply elementwise on two ndarrays. Broadcasting rules are applied if the arrays do not have the same shape:

In [213]:
a = np.array([8, -2, 9])
b = np.array([5, 8, -1])
np.add(a, b)

array([13,  6,  8])

In [214]:
np.subtract(a, b)

array([  3, -10,  10])

In [215]:
np.multiply(a, b)

array([ 40, -16,  -9])

In [216]:
np.maximum(a, b)

array([8, 8, 9])

In [217]:
# magnitude of a and sign of b
np.copysign(a, b)

array([ 8.,  2., -9.])

In [218]:
np.greater(a, b)

array([ True, False,  True])